### ISSUE TITLE
Description Lupo REST-Schnittstelle

### ISSUE THREAD

**Issue by HannesLUBW** [biggis-project/biggis-docs#12]
Hi,
I am not sure what you expect regarding the level of detail for the LUPO REST-Schnittstelle (biggis-docs/docs/data-sources/index.md). I would prefer to give Information on the URL:

- http://lupo-messwerte.appspot.com/lupo_luft_query?land=bw&limit=500&format=gme
and the parameters, especially "Land"= (bw | by | st | sh | th | de)

Do you expect something different? Currently I am waiting for the perimission of my boss to make the information public.

**Comment by vsimko** [comment]
Hi Hannes,
you could maybe look here http://biggis-project.eu/biggis-docs/demos/heatstress/
for inspiration. Please coordinate the LUPO-related docs with @frank-fzi

**Comment by HannesLUBW** [comment]
Thanks Viliam!
I just got the feedback of my Boss Wolfgang Schillinger. He doesnt want the REST -API URL to be public because it is not protected by authentification.

**Comment by vsimko** [comment]
ok, then you could add some simple token based authentication (token in the HTTP header).

**Comment by HannesLUBW** [comment]
Hi Viliam,
this is not possible yet. The Rest-Service is used by other clients (Webcomponents, Apps) which are not prepared to use tokens yet. We need to change this in the longer run. I dont expect this to happen before the BigGis project ends. But maybe we can public it later in 2018 and update the documentation than.
