### ISSUE TITLE
Picture Meteorological Station FZI

### ISSUE THREAD

**Issue by HannesLUBW** [biggis-project/biggis-docs#15]
Hi Viliam,
I would like to add a picture of the meteorological station at FZI in my description. Can you take a picture of it ? That would be great ! You can upload it in this folder:

biggis-docs/docs/data_sources/atmosphere/lubw/

I will add the link in the text.

**Comment by vsimko** [comment]
ok, I'll do it

**Comment by vsimko** [comment]
I made several photos today, and I'll send you a link so that you can pick yourself.

**Comment by HannesLUBW** [comment]
Great photos. Thanks for the effort!
