### ISSUE TITLE
please improve: biosphere/vitimeteo

### ISSUE THREAD

**Issue by vsimko** [biggis-project/biggis-docs#19]
please improve the following test:
https://github.com/biggis-project/biggis-docs/blob/master/docs/data-sources/biosphere/vitimeteo/index.md

probably  by refactoring some text and images from here:
https://github.com/biggis-project/biggis-docs/blob/master/docs/demos/invasive-species/index.md

**Comment by jkutterer** [comment]
I have added some text for the vitemetio data source.
